<h5 class="text-primary">CNAM (ARDAN)/Entrepreneur TPE</h5>
<h6 class="text-info">Décembre 2022 à Juin 2023, Toulon</h6>
<h5 class="text-primary">GRETA TOULON/Développeur Web PHP SYMFONY MySQL</h5>
<h6 class="text-info">Mars 2021 à Mai 2021, Toulon</h6>
<h5 class="text-primary">DEFI83 TOULON/Management de projet</h5>
<h6 class="text-info">2019, Toulon</h6>
<h5 class="text-primary">FITEC/Certificat de qualification professionnelle Développeur Java/JEE</h5>
<h6 class="text-info">Octobre 2010 à Octobre 2011, ILE-DE-FRANCE</h6>
<h5 class="text-primary">AXYA/Développeur NTIC en environnement Finance</h5>
<h6 class="text-info">2009, ILE-DE-FRANCE</h6>
<h5 class="text-primary">IAE Toulon/DESS Certificat Aptitude à l’Administration des Entreprises</h5>
<h6 class="text-info">2004, Toulon</h6>
<h5 class="text-primary">Université de Toulon et du Var/Maîtrise Electronique, Electrotechnique, Automatisme</h5>
<h6 class="text-info">1996, Toulon</h6>